Implemented_the_intersect_function
davidbenicek/raytracer pull request #25
Opened 2018-01-26 19:42 UTC by obimmatimothy

Look at the implementation of the intersect method for spheres

2018-01-28 16:22 UTC, davidbenicek requested changes
Looks good apart from that one tiny line

2018-01-28 16:22 UTC, davidbenicek commented on back_end/RayTracer/Models/Geometric/Sphere.cs
> +            //throw new NotImplementedException();
Can we get rid off this commented out line of code?

2018-01-28 18:14 UTC, obimmatimothy commented
I have Removed the Line of Commented Code

2018-01-28 18:16 UTC, davidbenicek approved these changes

2018-01-29 08:29 UTC, othmankh reviewed
The implementation seems to be right, but I wonder about the naming of variables, specially, the variable with name checker, are you sure about this naming ?

2018-01-29 10:29 UTC, othmankh approved these changes

2018-01-29 10:48 UTC, othmankh commented
The merge is done.

2018-01-29 10:52 UTC, merged